# Generated by Django 4.2.30 on 2026-09-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_featured_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
