# Generated by Django 4.2.30 on 2026-09-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_source_url_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
