# Generated by Django 4.2.30 on 2026-09-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
