# Generated by Django 4.2.30 on 2026-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
