# Generated by Django 4.2.30 on 2026-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('image', models.URLField(max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
    ]
