# Generated by Django 4.2.30 on 2026-09-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
